### ISSUE TITLE
scripting additional options on details view

### ISSUE THREAD

**Issue by slav123** [gmunhoz/CollieGallery#1]
Hi 

I'm just wondering if there is any way to hook up own functions / views over detailed views of image. I mean - let's say that I would like to add own icons next to "x" and "..." icons, or just display some meta data when tap on image ? 

If there is any "easy" way to do it ?

bdw: great project, works like a charm !

**Comment by gmunhoz** [comment]
Hi

I'm currently working on delegate functions to handle some events on your own and it will be available in the next few days. 

Thank you for your feedback!

**Comment by slav123** [comment]
I'm super excited about it!
