### ISSUE TITLE
Share feature

### ISSUE THREAD

**Issue by LaurentiuUngur** [gmunhoz/CollieGallery#4]
**Feature request**:
Would be cool if you can add share option. You can have into a corner a share icon and when you tap on it, to show default iOS share menu. As I know, in iOS share menu you also could have save image option.

_Thank you !_

**Comment by gmunhoz** [comment]
Hi

A share button would be really cool! I'll work on it for the next minor release.

Thank you for your feedback!

**Comment by LaurentiuUngur** [comment]
If you need any help please let me know ! Thanks !
