### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by TheCodeTalker** [gmunhoz/CollieGallery#7]
its crushing when you swap and press close button then crushing with this error "fatal error: Index out of range
![screen shot 2016-08-24 at 12 47 22 am](https://cloud.githubusercontent.com/assets/3683673/17906332/7a8c8a74-6994-11e6-83e6-ceb4244fb2a4.png)
"

**Comment by NikhilBatra-Proptiger** [comment]
This issue is caused because the scroll view is removed from superview and width is decreased to fixed constant which is quite less. 
You can easily solve this by deallocating scroll view delegate in view will disappear.

**Comment by nikhilbatra789** [comment]
This issue is caused because the scroll view is removed from superview and width is decreased to fixed constant which is quite less. 
You can easily solve this by deallocating scroll view delegate in view will disappear.
